In [2]:
import numpy as np

In [3]:
escalar = 5.679
vector = np.array([3,4,5,6])
matriz = np.array([[1,2],[3,4]])
tensor = np.array([
    [[1,2,3,30],[4,5,6,31],[7,8,9,32]],
    [[11,12,13,33],[14,15,16,34],[17,18,19,35]],
    [[21,22,23,36],[24,25,26,37],[27,28,29,38]],
])



In [5]:
vectorT = vector.T
print (vectorT)

[3 4 5 6]


In [14]:
matrizT = matriz.T
print (matrizT)

[[1 3]
 [2 4]]


In [8]:
tensorT = tensor.T
print (tensorT)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]

 [[30 33 36]
  [31 34 37]
  [32 35 38]]]


In [11]:
matrizT_t = matrizT.T
print (matrizt_t)

[[1 2]
 [3 4]]


In [13]:
tensorT_t = tensorT.T
print (tensorT_t)

[[[ 1  2  3 30]
  [ 4  5  6 31]
  [ 7  8  9 32]]

 [[11 12 13 33]
  [14 15 16 34]
  [17 18 19 35]]

 [[21 22 23 36]
  [24 25 26 37]
  [27 28 29 38]]]
