In [21]:
import numpy as np

In [29]:
escalar = 5.769
vector = np.array ([3,4,5,5,7])
matriz = np.array([[1,2], [3,4], [5,6], [8,16], [74,3]])

In [26]:
A = matriz.T + vector
print(A)

[[ 4  7 10]
 [ 5  8 11]]


In [27]:
matriz.T

array([[1, 3, 5],
       [2, 4, 6]])

In [30]:
C = matriz + 42
print(C)

[[ 43  44]
 [ 45  46]
 [ 47  48]
 [ 50  58]
 [116  45]]


In [32]:
## Ejercicio
W = matriz.T + vector
print(W)

[[ 4  7 10 13 81]
 [ 5  8 11 21 10]]


In [37]:
v_5 = np.random.randint(low = 3, high=5, size =(5, 5)) 
m_5 = np.random.randint(low = 1, high=9, size =(1,5)) 
print(m_5)


[[6 3 1 6 1]]
