In [3]:
import numpy as np
escalar = 5.679
vector = np.array([3,4])
matriz = np.array([[1,2],[3,4], [5,6]])

In [5]:
A = matriz * vector

In [6]:
B = matriz.dot(vector)

In [7]:
print(A)

[[ 3  8]
 [ 9 16]
 [15 24]]


In [9]:
print(B)

[11 25 39]


In [12]:
C = vector * matriz
print (C)

[[ 3  8]
 [ 9 16]
 [15 24]]
