In [2]:
import numpy as np

In [4]:
matriz = np.array ([[1,0,0],
                   [0,1,0],
                   [0,0,1],]
                
                  )

print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
print(matriz[:,0].dot(matriz[:,1]))

0


In [6]:
print(matriz[:,0].dot(matriz[:,2]))

0


In [7]:
print(matriz[:,1].dot(matriz[:,2]))

0


In [9]:
print (np.linalg.norm(matriz[:,0]))
print (np.linalg.norm(matriz[:,1]))
print (np.linalg.norm(matriz[:,2]))

1.0
1.0
1.0


In [11]:
print(matriz[0,:].dot(matriz[1,:]))
print(matriz[0,:].dot(matriz[2,:]))
print(matriz[1,:].dot(matriz[2,:]))

0
0
0


In [12]:
A = np.array ([[np.cos(100), -np.sin(100)],
              [np.sin(100),np.cos(100)]])

print(A)

[[ 0.86231887  0.50636564]
 [-0.50636564  0.86231887]]


In [13]:
print (np.linalg.norm(A[0,:]))
print (np.linalg.norm(A[1,:]))
print (np.linalg.norm(A[:,0]))
print (np.linalg.norm(A[:,0]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [15]:
print (A[0,:].dot(A[1,:]))
print (A[:,0].dot(A[:,1]))

0.0
0.0
