In [2]:
import numpy as np

In [16]:
identidad = np.eye(4)

In [17]:
print (identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
vector = np.array([[2],[3],[5],[7]])

In [20]:
print (identidad.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


In [21]:
A = np.array ([[1,0,1],[0,1,1],[-1,1,1]])

In [22]:
print(A)

[[ 1  0  1]
 [ 0  1  1]
 [-1  1  1]]


In [24]:
inversa_A = np.linalg.inv (A)

In [25]:
print (A.dot(inversa_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
singular = np.array([[1,1],[1,1]])

In [28]:
print(singular)

[[1 1]
 [1 1]]


In [29]:
print(np.linalg.inv(singular))

LinAlgError: Singular matrix