In [2]:
import numpy as np

In [8]:
matriz1 = np.random.randint(1, 50, size=(3, 3, 3))

In [10]:
print(matriz1)

[[[16 21 12]
  [18 34 13]
  [14 17 42]]

 [[17 19 23]
  [26 11 46]
  [21 37  8]]

 [[13 11 10]
  [33 28 29]
  [24 40 16]]]


In [12]:
A = np.array ([[2,3],[5,7],[11,13]])
B = np.array ([[1,3],[2,1]])

In [13]:
print(A)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [15]:
print(B)

[[1 3]
 [2 1]]


In [16]:
AB_T = A.dot(B).T

In [18]:
B_TA_T= B.T.dot(A.T)

In [19]:
print (AB_T == B_TA_T)

[[ True  True  True]
 [ True  True  True]]
