In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array ([[3,2], [4,1]])
print(X)

[[3 2]
 [4 1]]


In [3]:
autovalores, autovectores = np.linalg.eig (X)
print (autovalores)
print(autovectores)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [8]:
A_cal= autovalores.dot (np.diag(autovalores)).dot (np.linalg.inv(autovectores))

In [9]:
print(A_cal)

[22.82487005 12.53046901]


In [10]:
A = np.array([[3,2],[2,3]])
print(A)

[[3 2]
 [2 3]]


In [12]:
AT = A.T
print(AT)

[[3 2]
 [2 3]]


In [14]:
print (A==AT)

[[ True  True]
 [ True  True]]
